apiVersion: v1
kind: BuildConfig
metadata:
  name: fisdemo-gatewaypipeline
  labels:
    name: fisdemo-gatewaypipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "fisgateway-service", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'build'\nopenshiftBuild(buildConfig: 'fisgateway-service', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'fisgateway-service')\nopenshiftScale(deploymentConfig: 'fisgateway-service',replicaCount: '1')\n}"
  output:
  resources:
  postCommit: